version: "3.3"

services:
  main:
    network_mode: "host"
    image: notify_changed_ip:${NOTIFY_IP_VERSION:-latest}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file: .env
